[app]
title = Sifre Uretici
package.name = sifre_uretici
package.domain = org.kivy
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy
orientation = portrait
osx.python_version = 3
fullscreen = 1
android.permissions = INTERNET
android.api = 31
android.ndk = 25b
android.ndk_path = 
android.sdk_path = 
android.gradle_dependencies = 
android.gradle_dependencies = androidx.appcompat:appcompat:1.0.2
android.archs = arm64-v8a,armeabi-v7a
android.minapi = 21
android.build_tools_version = 33.0.2
