name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Kodları klonla
        uses: actions/checkout@v4

      - name: Python 3.10.18 kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.18'

      - name: Sistem bağımlılıklarını yükle
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk wget curl libgl1-mesa-dev git python3-pip

      - name: Buildozer ve Cython kur
        run: |
          python -m pip install --upgrade pip setuptools Cython virtualenv
          pip install buildozer

      - name: Android SDK ve NDK ayarları
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip -d ~/.buildozer/android/platform/cmdline-tools
          mv ~/.buildozer/android/platform/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/cmdline-tools/latest

          echo "y" | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: PATH ayarları
        run: |
          echo "$HOME/.buildozer/android/platform/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: APK oluştur
        run: |
          buildozer android debug
