name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Buildozer ve bağımlılıkları yükle
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libncurses6 libtinfo5 libffi-dev libssl-dev \
                              libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
                              pkg-config git zip unzip openjdk-17-jdk

          python -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Android SDK & cmdline-tools indir
        run: |
          mkdir -p /home/runner/.android/cmdline-tools
          cd /home/runner/.android/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d latest
          rm sdk-tools.zip
          yes | /home/runner/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/.android "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;25.2.9519653"

      - name: Ortam değişkenleri tanımla
        run: |
          echo "ANDROID_HOME=/home/runner/.android" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/home/runner/.android/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=/home/runner/.android/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: APK üret
        run: |
          buildozer android debug
