name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.18"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y \
          zip unzip openjdk-17-jdk \
          python3-pip libffi-dev libssl-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
          zlib1g-dev libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
          libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev \
          libxi-dev libsmpeg-dev libjpeg-dev libfreetype6-dev \
          pkg-config libunwind-dev libgstreamer1.0-dev

        pip install --upgrade pip
        pip install buildozer Cython

    - name: Setup Android SDK & NDK
      run: |
        mkdir -p $HOME/.android
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -o cmdline-tools.zip
        rm cmdline-tools.zip

        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/

        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        export PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;25.1.8937393"

    - name: Build APK
      run: |
        buildozer android debug
