name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v4

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gereklilikleri yükle
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libncurses5
        pip install --upgrade pip setuptools Cython virtualenv
        pip install buildozer

    - name: APK üret
      run: |
        buildozer android debug

    - name: APK'yi yükle
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: bin/*.apk
