name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.18

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libbz2-dev liblzma-dev \
            libncursesw5-dev libsqlite3-dev libreadline-dev libgdbm-dev \
            zlib1g-dev openjdk-17-jdk unzip libnss3 pulseaudio \
            libtiff5 libjpeg8-dev libopenjp2-7 libopenjp2-7-dev \
            libavcodec-dev libavformat-dev libswscale-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswresample-dev libavdevice-dev \
            libfreetype6-dev libffi-dev libgstreamer1.0-dev \
            libmtdev-dev autoconf libtool pkg-config build-essential \
            git zip python3-pip libegl1-mesa

      - name: Install latest Buildozer from GitHub (fixes SDK issues)
        run: |
          pip install --upgrade pip setuptools
          pip install cython
          pip install git+https://github.com/kivy/buildozer.git

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug
