name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10.18
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.18'

    - name: Set Java 17 (uyumlu versiyon)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          git \
          zip \
          unzip \
          libncursesw6 \
          libtinfo6 \
          libunwind-dev \
          libssl-dev \
          libffi-dev \
          libz-dev \
          openjdk-17-jdk \
          python3-pip

    - name: Upgrade pip & install Cython
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install Cython

    - name: Install buildozer
      run: |
        pip install buildozer

    - name: Initialize buildozer (if .buildozer dir doesn't exist)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build the APK
      run: |
        buildozer android debug
