name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libavcodec-dev libavformat-dev libswscale-dev \
            libjpeg-dev libfreetype6-dev libncurses5 \
            build-essential git python3-pip curl

          pip install --upgrade pip setuptools wheel Cython virtualenv
          pip install buildozer

          mkdir -p ~/.buildozer/android/platform
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q commandlinetools.zip -d ~/.buildozer/android/platform/
          mkdir -p ~/.buildozer/android/platform/cmdline-tools
          mv ~/.buildozer/android/platform/cmdline-tools/* ~/.buildozer/android/platform/cmdline-tools/latest
          yes | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;25.2.9519653" "cmdline-tools;latest"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: newsifre.apk
          path: bin/*.apk
