name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v4

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: SDK ve Build-Tools kur (AIDL dahil)
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk unzip wget git python3-pip zip
        mkdir -p ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/
        mv ~/.buildozer/android/platform/cmdline-tools ~/.buildozer/android/platform/tools
        yes | ~/.buildozer/android/platform/tools/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Buildozer ve gereklilikleri yükle
      run: |
        pip install --upgrade pip setuptools Cython virtualenv
        pip install buildozer

    - name: APK üret
      run: |
        buildozer android debug

    - name: APK dosyasını yükle
      uses: actions/upload-artifact@v4
      with:
        name: sifre_apk.apk
        path: bin/*.apk
