name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python 3.10.18'i ayarla
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.18

      - name: Sistem bağımlılıklarını kur
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev libsqlite3-dev libncursesw5 libncurses5

      - name: Buildozer ve cython kur
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Java 17 kullan
        run: |
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java 1
          sudo update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
          java -version

      - name: Android SDK ve NDK kur
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip -d ~/.buildozer/android/platform/cmdline-tools
          mv ~/.buildozer/android/platform/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/cmdline-tools/latest

          echo "y" | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: buildozer.spec dosyasını kontrol et
        run: |
          ls
          cat buildozer.spec || echo "buildozer.spec yok!"

      - name: APK derle
        run: |
          buildozer android debug
